### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by raffazizzi** [nulib/react-media-player#49]
This looks like a wonderful viewer! Would love to experiment with it for projects at https://github.com/umd-mith/. Do you have a license in mind for the code?

**Comment by mathewjordan** [comment]
@raffazizzi That's a great question. I think we'd lean MIT License though not 100% sure. It's definitely free for open use. As a heads up, we may be renaming this to something a little less generic in the near future which would include renaming the NPM package. We'll inform out about that when it happens. Thanks for your interest. We'd appreciate any feedback!

**Comment by mathewjordan** [comment]
@raffazizzi Curious, how'd you come across this repo?

**Comment by raffazizzi** [comment]
I was told that the Univ of Tennessee worked on a IIIF A/V viewer, couldn't find much on Google, but ended up on your GitHub profile and saw this repo there 😀

**Comment by mathewjordan** [comment]
Ah, yes! This is the Tennessee IIIF/AV project https://rfta.lib.utk.edu/ that may have been mentioned, source code here: https://github.com/utkdigitalinitiatives/canopy. The viewer in the canopy pretty is pretty tied into that Gatsby repo. This viewer hopes to do some of what the RFTA project was doing but be more modular and work across manifest canvases.

**Comment by mathewjordan** [comment]
Hi @raffazizzi. We have added the MIT License. Thank you again for creating the issue.
